// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AdminStats struct {
	TotalUsers         int                 `json:"totalUsers"`
	TotalFiles         int                 `json:"totalFiles"`
	TotalStorage       int                 `json:"totalStorage"`
	UniqueFiles        int                 `json:"uniqueFiles"`
	DuplicateFiles     int                 `json:"duplicateFiles"`
	StorageEfficiency  float64             `json:"storageEfficiency"`
	ActiveUsers        int                 `json:"activeUsers"`
	NewUsersToday      int                 `json:"newUsersToday"`
	DeduplicationStats *DeduplicationStats `json:"deduplicationStats"`
}

type DeduplicationStats struct {
	TotalFileRecords    int     `json:"totalFileRecords"`
	UniqueFileHashes    int     `json:"uniqueFileHashes"`
	DuplicateRecords    int     `json:"duplicateRecords"`
	StorageSaved        int     `json:"storageSaved"`
	StorageSavedPercent float64 `json:"storageSavedPercent"`
	CostSavingsUsd      float64 `json:"costSavingsUSD"`
}

type FileShareStats struct {
	DownloadCount   int            `json:"downloadCount"`
	RecentDownloads []*DownloadLog `json:"recentDownloads"`
}

type MimeTypeCategories struct {
	Documents []string `json:"documents"`
	Images    []string `json:"images"`
	Videos    []string `json:"videos"`
	Audio     []string `json:"audio"`
	Archives  []string `json:"archives"`
	Code      []string `json:"code"`
}

type SearchResult struct {
	Files      []*File `json:"files"`
	TotalCount int     `json:"totalCount"`
	HasMore    bool    `json:"hasMore"`
}

type SystemHealth struct {
	DatabaseStatus string  `json:"databaseStatus"`
	StorageStatus  string  `json:"storageStatus"`
	Uptime         string  `json:"uptime"`
	MemoryUsage    float64 `json:"memoryUsage"`
	DiskUsage      float64 `json:"diskUsage"`
	LastBackup     *string `json:"lastBackup,omitempty"`
}

type UserStats struct {
	UserID      string  `json:"userId"`
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	TotalFiles  int     `json:"totalFiles"`
	StorageUsed int     `json:"storageUsed"`
	LastLogin   *string `json:"lastLogin,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	IsActive    bool    `json:"isActive"`
}
